### PR TITLE
Enable truffle ruby support

### PR DESCRIPTION
**Pull request by gogainda**
@eregon I run the test suite locally, it works fine for me

### CODE REVIEW

**Comment by gogainda** [comment]
```
icalendar % bundler exec rake                                                     [7/08/20 | 4:31:30]
/Users/novoi/.rubies/truffleruby-dev/bin/truffleruby -I/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib:/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-support-3.9.3/lib /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 24115
............................................................................................................................................................................W, [2020-08-07T16:32:15.137000 #27187]  WARN -- : No method "sequence=" for component #<Icalendar::Timezone:0x3bfa0>. Appending to custom.
W, [2020-08-07T16:32:15.282000 #27187]  WARN -- : No method "summary=" for component #<Icalendar::Component:0x3c1c8>. Appending to custom.
W, [2020-08-07T16:32:15.284000 #27187]  WARN -- : No method "description=" for component #<Icalendar::Component:0x3c1c8>. Appending to custom.
W, [2020-08-07T16:32:15.287000 #27187]  WARN -- : No method "url=" for component #<Icalendar::Component:0x3c1c8>. Appending to custom.
..........................

Finished in 23.39 seconds (files took 5.8 seconds to load)
198 examples, 0 failures

Randomized with seed 24115

Coverage report generated for RSpec to /Users/novoi/tmp/icalendar/coverage. 1009 / 1066 LOC (94.65%) covered.
icalendar 2.6.1 built to pkg/icalendar-2.6.1.gem.

icalendar % ruby -v                                                               [7/08/20 | 4:32:27]
truffleruby 20.3.0-dev-9220194b, like ruby 2.6.6, GraalVM CE Native [x86_64-darwin]
```

**Comment by eregon** [comment]
It seems TravisCI is not running on recent master and on this PR:
https://github.com/icalendar/icalendar/commits/master
Maybe it needs to be re-enabled?

**Comment by eregon** [comment]
Actually it ran here but somehow doesn't get reported to GitHub:
https://travis-ci.org/github/icalendar/icalendar/builds/715865031

**Comment by rahearn** [comment]
Cool, I hadn't heard of TruffleRuby yet.

**Pull request merged**
