### PR TITLE
Icalendar new

### PR DESCRIPTION
**Pull request by ron**

### CODE REVIEW

**Comment by espen** [comment]
Great PR. Thanks for your contribution to the project. Could you perhaps provide some details on what the changes are, modify the PR title to something more descriptive, and add some links for this?

**Comment by ron** [comment]
Hi @espen this is functionality we added a few years ago in our own fork, we needed to update the gem for ruby 3. I made this PR by accident.
But if you like the functionality we can clean it up for you

**Comment by espen** [comment]
I am not the maintainer but all PRs are welcome :) If this means you can use the gem instead of relying on your fork that could be useful for you I guess. I am not that familiar with the availability part of icalendar but I see that it can be useful for others.

**Comment by rahearn** [comment]
Hi @ron, thanks for the PR (even if by accident). I'm interested in the functionality, though it looks like it does need to be cleaned up a bit. Also, which RFC(s) is this implementing? Is it all in 7953? I'd like to read up a bit more before saying yes we definitely want it included here, vs as a complementary gem like https://github.com/icalendar/icalendar-recurrence

**Comment by rahearn** [comment]
Closing since there's been no response

**Pull request closed without merging**
